### ISSUE TITLE
Mistaken 3D Assumption for Set11 Dataset

### ISSUE THREAD

**Issue by AnirudhNarsipur** [likesum/unsupimg#1]
For the 'Foreman' and 'Parrot' files in the Set11 dataset, the test script tries to read it as a 3D array. This results in an error ('Extra dimensions'). 

Treating these files like the others fixes this.

**Comment by ayanc** [comment]
Did you use the download script to get the test sets ? We have the clause in there because the test set version we are using (from the ISTA net paper repo) has those two images as three channel RGB files.

But if you have a version of the test set where all files are already grayscale, changing the code in the way you did works!
